export const categories = [
  { id: 'business', display: 'Business', icon: '💼' },
  { id: 'entertainment', display: 'Entertainment', icon: '🎬' },
  { id: 'general', display: 'General', icon: '📰' },
  { id: 'health', display: 'Health', icon: '🏥' },
  { id: 'science', display: 'Science', icon: '🔬' },
  { id: 'sports', display: 'Sports', icon: '⚽' },
  { id: 'technology', display: 'Technology', icon: '💻' },
  { id: 'politics', display: 'Politics', icon: '🏛️' },
  { id: 'environment', display: 'Environment', icon: '🌱' },
  { id: 'education', display: 'Education', icon: '📚' },
];

export const indianStates = [
  { id: 'andhra-pradesh', name: 'Andhra Pradesh' },
  { id: 'arunachal-pradesh', name: 'Arunachal Pradesh' },
  { id: 'assam', name: 'Assam' },
  { id: 'bihar', name: 'Bihar' },
  { id: 'chhattisgarh', name: 'Chhattisgarh' },
  { id: 'goa', name: 'Goa' },
  { id: 'gujarat', name: 'Gujarat' },
  { id: 'haryana', name: 'Haryana' },
  { id: 'himachal-pradesh', name: 'Himachal Pradesh' },
  { id: 'jharkhand', name: 'Jharkhand' },
  { id: 'karnataka', name: 'Karnataka' },
  { id: 'kerala', name: 'Kerala' },
  { id: 'madhya-pradesh', name: 'Madhya Pradesh' },
  { id: 'maharashtra', name: 'Maharashtra' },
  { id: 'manipur', name: 'Manipur' },
  { id: 'meghalaya', name: 'Meghalaya' },
  { id: 'mizoram', name: 'Mizoram' },
  { id: 'nagaland', name: 'Nagaland' },
  { id: 'odisha', name: 'Odisha' },
  { id: 'punjab', name: 'Punjab' },
  { id: 'rajasthan', name: 'Rajasthan' },
  { id: 'sikkim', name: 'Sikkim' },
  { id: 'tamil-nadu', name: 'Tamil Nadu' },
  { id: 'telangana', name: 'Telangana' },
  { id: 'tripura', name: 'Tripura' },
  { id: 'uttar-pradesh', name: 'Uttar Pradesh' },
  { id: 'uttarakhand', name: 'Uttarakhand' },
  { id: 'west-bengal', name: 'West Bengal' },
  { id: 'andaman-nicobar', name: 'Andaman and Nicobar Islands' },
  { id: 'chandigarh', name: 'Chandigarh' },
  { id: 'dadra-nagar-haveli', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { id: 'delhi', name: 'Delhi' },
  { id: 'jammu-kashmir', name: 'Jammu and Kashmir' },
  { id: 'ladakh', name: 'Ladakh' },
  { id: 'lakshadweep', name: 'Lakshadweep' },
  { id: 'puducherry', name: 'Puducherry' },
];
